/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ShrubberyCreationForm.cpp                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: likong <likong@student.hive.fi>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/10/01 13:15:46 by likong            #+#    #+#             */
/*   Updated: 2025/10/01 13:15:47 by likong           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ShrubberyCreationForm.hpp"

constexpr const char ASCII_TREE[] =
R"(..................................................
......................@@...........................
.....................@@@@..........................
....................@@@@@@.........................
...................@@@@@@@@........................
..................@@@@@@@@@@.......................
.................@@@@@@@@@@@@......................
................@@@@@@@@@@@@@@.....................
...............@@@@@@@@@@@@@@@@....................
..............@@@@@@@@@@@@@@@@@@...................
.............@@@@@@@@@@@@@@@@@@@@..................
............@@@@@@@@@@@@@@@@@@@@@@.................
...........@@@@@@@@@@@@@@@@@@@@@@@@................
..........@@@@@@@@@@@@@@@@@@@@@@@@@@...............
.........@@@@@@@@@@@@@@@@@@@@@@@@@@@@..............
.....................@@@@@@........................
.....................@@@@@@........................
.....................@@@@@@........................
.....................@@@@@@........................
.....................@@@@@@........................
.....................@@@@@@........................
..................................................
)";

ShrubberyCreationForm::ShrubberyCreationForm(): AForm("ShrubberyCreationForm", 145, 137, "unknown") {}

ShrubberyCreationForm::ShrubberyCreationForm(const std::string& target): AForm("ShrubberyCreation", 145, 137, target) {}

ShrubberyCreationForm::ShrubberyCreationForm(const ShrubberyCreationForm& copy): AForm(copy) {}

ShrubberyCreationForm& ShrubberyCreationForm::operator= (const ShrubberyCreationForm& copy) {
	if (this != &copy)
		AForm::operator=(copy);
	return *this;
}

ShrubberyCreationForm::~ShrubberyCreationForm(){}

void ShrubberyCreationForm::executeThis() const {
	std::ofstream output(this->getTarget() + "_shrubbery");

	if (!output)
		throw std::runtime_error("Error: Cannot open the file in Shrubbery class");
	output << ASCII_TREE;
	output.close();
}
